### PR TITLE
Task4 - 10web

### PR DESCRIPTION
**Pull request by Terminal017**
## 概要
10个网站+1个学长修改的

## 检查清单
- [x] 如果进行了代码更改，则它们已经过测试。

## 补充说明
1、一些产生错误的网站是由于它们需要**登录**。

### CODE REVIEW

**Comment by foxwhite25** [comment]
TODO for me:
- [ ] 1422, 1430 Wrong page type on sitemap 
- [ ] Check 1429, 1427

**Comment by Terminal017** [comment]
For 1427, my connection to the site was erratic, and actually my computer sometimes can pick up some news.
For 1429, the site's SSL certificate expired recently (a little unlucky i think).
For these two sites I will submit two new sites later.
For 1422 and 1430, I will try to fix and commit a change soon.

**Pull request merged**
